# TODO(RKM 2019-11-20) Make the docker push only happen for tagged builds on master

dist: bionic

language: python
python:
  - "3.7"

cache: pip

before_install:
  - pip install -r requirements-dev.txt
  - pre-commit install
  - pre-commit run --all-files

install:
  - pip install -r requirements.txt
  # - pip install --upgrade git+https://github.com/alan-turing-institute/aviary.git@develop#egg=aviary

script:
  - pytest -vrs --ignore=./tests/integration ./tests
  # Pre-build the BlueBird docker image
  - docker build .
  - pytest -vrs ./tests/integration
# TODO(RKM 2019-11-23) Re-enable after integration tests passing
# after_success:
#   - bash $BLUEBIRD_HOME/.travis-build.sh
