# TODO(RKM 2019-11-20) Make the docker push only happen for tagged builds on master

branches:
  only:
    - master
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - feature/mach-coll-integration-2

dist: bionic

language: python
python:
  - "3.7"

cache: pip

before_install:
  - pip install -r requirements-dev.txt
  - pre-commit install
  # Re-enable once behaving
  - pre-commit run # --all-files

install:
  - pip install -r requirements.txt

script:
  - pytest -rs --ignore=./tests/integration ./tests
  # TODO(RKM 2019-11-21) Re-enable after integration tests are refactored
  # - pytest -rs ./tests/integration

after_success:
  - bash $BLUEBIRD_HOME/.travis-build.sh
