
branches:
  only:
  - master
  - /^release\/.*$/
  - /^hotfix\/.*$/

language: python
python:
  - "3.6"

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest -rs tests
