# whitelist
branches:
  only:
  - master
  - /^release\/.*$/

language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest ./tests/
